### ISSUE TITLE
Gdk.TouchEvent seems to have wrong class definition (Exception thrown)

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [GtkSharp/GtkSharp#299]
When I try to implement the TouchEvent handler, as soon as I try to use the TouchEvent in code I get  below exception thrown.
The exception is pretty self explaining, so I think this is a bug that needs to be fixed. 

Running GTK version 3.24.5-1+rpt2 on raspberry, (Netcore 5.0) Using latest Gtksharp version 3.24.24.34

Marshaling touch-event signal
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Unable to cast object of type 'Gdk.Event' to type 'Gdk.EventTouch'.
   at Gtk.TouchEventArgs.get_Event()
   at ReaderFirmware.ViewsGtk.GraphicsMenu.Fixed_GraphicsMenu.CardImage_TouchEvent(Object o, TouchEventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at Gtk.Application.Run()
   at ReaderFirmware.MessageDispatch.GtkMainThread()
   at ReaderFirmware.MessageDispatch.<Start>b__11_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Want100Cookies** [comment]
I also encoutered this bug running the same gtksharp version with net6.0 under both windows and linux. For now I workarround by overriding the widget and implementing the `protected override bool OnTouchEvent(Gdk.EventTouch evnt)` and firing a custom event handler.

**Comment by lytico** [comment]
https://docs.gtk.org/gtk3/signal.Widget.touch-event.html

defines: 
``
gboolean
touch_event (
  GtkWidget* self,
  GdkEvent* object,
  gpointer user_data
)
``

definition in 
GtkSharp-api.xml

is:

``
      <signal name="TouchEvent" cname="touch-event" when="LAST" field_name="touch_event">
        <return-type type="gboolean" />
        <parameters>
          <parameter type="GdkEventTouch*" name="event" />
        </parameters>
      </signal>
``
