### ISSUE TITLE
System.DllNotFoundException thrown when building a .NET 4.7.2 Framework app with GtkSharp

### ISSUE THREAD

**Issue by patrickmurray18** [GtkSharp/GtkSharp#390]
I am building from Windows (VS) and testing the result on both Windows 10 and my Linux VMs. I have a **dotnet6** project and it can use GtkSharp just fine published for both Windows and Linux.

However it does not seem to work with a the same project targeting **.NET Framework 4.7.2**, I get this same error on both Windows and Linux:

> The type initializer for 'Gtk.Application' threw an exception. ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
>    at GLibrary.Load(Library library)
>    at Gtk.Application..cctor()
>    --- End of inner exception stack trace ---
> ...

Between the two projects, I use a different Linux OS for the .NET Framework 4.7.2 version but I'm testing the projects on the same Windows machine.

I tried `sudo apt install libgtk-3-0` on the Linux machine but it made no difference.

I cannot find any of the dlls from the error in the outputs of either versions of the project.

I know there is already issue https://github.com/GtkSharp/GtkSharp/issues/337 but that seems different (that one is about publishing to Windows from Linux and they seem to see `libgtk-3-0.dll` in the output).

**Comment by patrickmurray18** [comment]
Actually, apologies, it seems that the issue does not occur on Linux. This is a problem for Windows only.
