### ISSUE TITLE
FileChooser Filename throws exception in .NET 7 app on latest 64 bit Raspberry PI OS

### ISSUE THREAD

**Issue by g9tec** [GtkSharp/GtkSharp#393]
Have been using the FileChooser in my .NET 6 app on the previous Raspberry PI OS (not sure if it was 32 or 64 bit). Upgraded to .NET 7 and latest 64 bit OS and now it throws the following exception whenever I try to get the Filename from the FileChooser. Note that URI works. Also, the stack trace show PreviewFilename, I changed to that just to see if it made a difference, which it did not.

Marshaling response signal
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> GLib.GException: Invalid byte sequence in conversion input
   at GLib.Marshaller.FilenamePtrToString(IntPtr ptr)
   at GLib.Marshaller.FilenamePtrToStringGFree(IntPtr ptr)
   at Gtk.FileChooserDialog.get_PreviewFilename()
   at G9.Components.UserInterface.GTK.FileDialogImpl._dialog_Response(Object o, ResponseArgs args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at Gtk.Application.Run()
   at G9Server.Program.Main(String[] args) in C:\Users\Dave\Documents\GitHub\src\Apps\G9Server\Program.cs:line 221

**Comment by bcr** [comment]
I have the same problem with .NET 7.0.202 on an M1 Mac with macOS 12.6.4. When you touch the `Filename` property it throws this exception.

```
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> GLib.GException: Invalid byte sequence in conversion input
   at GLib.Marshaller.FilenamePtrToString(IntPtr ptr)
   at GLib.Marshaller.FilenamePtrToStringGFree(IntPtr ptr)
   at Gtk.FileChooserDialog.get_Filename()
```

**Comment by dsoronda** [comment]
Can you add simple code example (main with few lines of code) so I can try to reproduce issue. Thanks

**Comment by cameronwhite** [comment]
This sounds a lot like #346, which I think is in the latest nuget release, but perhaps there's a similar issue still?

**Comment by bcr** [comment]
> Can you add simple code example (main with few lines of code) so I can try to reproduce issue. Thanks

https://github.com/bcr/GtkSharpFileChooserProblem

**Comment by dsoronda** [comment]
Works fine on Ubuntu 22.10 x64. 
Fails on Orange Pi 5 (Debian) `Linux orangepi5 5.10.110-rockchip-rk3588 #1.1.0 SMP Fri Jan 6 14:00:53 CST 2023 aarch64 aarch64 aarch64 GNU/Linux`

```
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> GLib.GException: Invalid byte sequence in conversion input
   at GLib.Marshaller.FilenamePtrToString(IntPtr ptr)
   at GLib.Marshaller.FilenamePtrToStringGFree(IntPtr ptr)
   at Gtk.FileChooserDialog.get_Filename()
   at GtkSharpFileChooserProblem.MainWindow.Button1_Clicked(Object sender, EventArgs a) in /home/orangepi/1/GtkSharpFileChooserProblem/MainWindow.cs:line 35
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at Gtk.Application.Run()
   at GtkSharpFileChooserProblem.Program.Main(String[] args) in /home/orangepi/1/GtkSharpFileChooserProblem/Program.cs:line 20

>$ dotnet list package
Project 'GtkSharpFileChooserProblem' has the following package references
   [net7.0]: 
   Top-level Package      Requested   Resolved  
   > GtkSharp             3.24.24.*   3.24.24.38
```

I'll try to compile GtkSharp locally with debug and reference libraries and try to catch error in debug.

**Comment by bcr** [comment]
Looking at the stack trace, it seems like we get hurt in `GLib.Marshaller.FilenamePtrToString` which just wraps `g_filename_to_utf8`. It may be the case that instrumenting the contents of `ptr` yields something interesting (if the string is not \0 terminated or there's some other funk in it for some reason.)

**Comment by bcr** [comment]
I checked my `locale` info and it's all UTF-8. I don't know if that's a potential difference between the working and non-working cases (you'd think it would Extra Good if your locale is UTF-8 though.)

**Comment by bcr** [comment]
I think this is about as simple as we can make it:

```csharp
public static void Main(string[] args)
{
    var ptr = GLib.Marshaller.StringToFilenamePtr("/foo/bar");
}
```

```
Unhandled exception. GLib.GException: Invalid byte sequence in conversion input
   at GLib.Marshaller.StringToFilenamePtr(String str)
   at GtkSharpFileChooserProblem.Program.Main(String[] args) in /Users/blake/Source/bcr/GtkSharpFileChooserProblem/Program.cs:line 11
```
All roads lead to `g_filename_from_utf8`

* Bad data in ptr of some sort (no trailing NUL?)?
* `(IntPtr)(-1)` is not producing -1?

**Comment by bcr** [comment]
The following code works on my machine (`error` is NULL and the function returns a valid string)

```c
#include <stdio.h>

#include <glib.h>

int main(void)
{
    const gchar* path = "/foo/bar";
    GError* error = NULL;
    gchar* result = NULL;

    result = g_filename_to_utf8(path, -1, NULL, NULL, &error);

    printf("result = %p, error = %p\n", result, error);

    if ((error == NULL) && (result != NULL))
    {
        printf("input was <%s> output is <%s>\n", path, result);
    }

    return 0;
}
```
```
➜  glibtest ./a.out    
result = 0x6000039500b0, error = 0x0
input was </foo/bar> output is </foo/bar>
```

**Comment by dsoronda** [comment]
This is code from `Marshaller.cs`

~~~csharp
	[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		delegate IntPtr d_g_filename_to_utf8(IntPtr mem, IntPtr len, IntPtr read, out IntPtr written, out IntPtr error);
		static d_g_filename_to_utf8 g_filename_to_utf8 = FuncLoader.LoadFunction<d_g_filename_to_utf8>(FuncLoader.GetProcAddress(GLibrary.Load(Library.GLib), "g_filename_to_utf8"));
		
		public static string FilenamePtrToString (IntPtr ptr) 
		{
			if (ptr == IntPtr.Zero) return null;
			
			IntPtr utf8 = g_filename_to_utf8 (ptr, (IntPtr)(-1), IntPtr.Zero, out _, out var error);

			if (error != IntPtr.Zero)
				throw new GLib.GException (error);
			return Utf8PtrToString (utf8);
		}
~~~

According to [GLib-filename_to_utf8](https://docs.gtk.org/glib/func.filename_to_utf8.html) bytes_read can be null.

Same as in @bcr example above:
~~~c
  result = g_filename_to_utf8(path, -1, NULL, NULL, &error);
~~~

So maybe #346 should be changed to :
~~~csharp
		public static string FilenamePtrToString (IntPtr ptr) 
		{
			if (ptr == IntPtr.Zero) return null;
			
			IntPtr utf8 = g_filename_to_utf8 (ptr, (IntPtr)(-1), null, out _, out var error);

			if (error != IntPtr.Zero)
				throw new GLib.GException (error);
			return Utf8PtrToString (utf8);
		}
~~~

I don't have much experience in unsafe C# so maybe someone else can give better solution.

**Comment by bcr** [comment]
I think we are on the right track here. It seems like a difference between x64 vs. arm64 marshaling of gssize through IntPtr and the interpretation of -1.

**Comment by bcr** [comment]
#398 seems like the same problem

**Comment by cyanfish** [comment]
This seems to be fixed by https://github.com/GtkSharp/GtkSharp/pull/346 and in GtkSharp/GLibSharp 3.24.24.95. For those using Eto, it currently depends on 3.24.24.38 which needs an upgrade.
